### ISSUE TITLE
Persisting roomMessage listeners

### ISSUE THREAD

**Issue by iamshouvikmitra** [an-sh/chat-service#23]
Hi @an-sh ,
I am trying to implement slack like chat application where an user will have multiple chatrooms created. As far as I understand, the client needs to be joined in a room to be able to listen for event inside the room. 

My question is what is the best way to let a client know that a new message was received in any of the rooms the client is a part of?

In order to achieve this, do I join each room while initializing the client web app by looping over the roomId(s) from dB, or is there a standard way to achieve this. 

There can a lot of rooms (~100) a client will be a part of at a given moment. So, Is there a hard limit to the number of room a client can join?

**Comment by serhiiivan** [comment]
Hi @iamshouvikmitra 

My name is Serhii from Ukraine and I am a Software Engineer. Do you know "Eric Dominic" by any chance? https://www.linkedin.com/in/eric-di-domenico/

Eric (@qwertme) hired me on Upwork and I worked on "RV Care" and "Virtual Briefing Center" project with Ruby on Rails. Recently, I was not able to dedicate much time to these projects because of personal problems. Due to this simple reason, he pressed to refund $2350 on Upwork. How he is a thief! I cannot tolerate him.

I am an old person and have families so I am working hard. If possible, I would like you to judge this problem.

Thank you,
Serhii
