### ISSUE TITLE
Clarification question about relation between userlist, adminlist, whitelist, blacklist

### ISSUE THREAD

**Issue by 1van-rus** [an-sh/chat-service#6]
I am writing my own MySQLState plugin based on MemoryState. And it is not clear how userlist, adminlist, whitelist, and blacklist related to each other.

**Comment by an-sh** [comment]
Each room has a set of lists and they are used for checking user
permissions in that room. There are two modes for a room
blacklist/whitelist, and the corresponding list is checked when an user
tries to join a room. Then for every room related command a
userlist/adminlist is checked. Also an userlist unlike others is not a
persistent entity and depends on the current server state. In case when
a server crushes and starts again, it will reflect an invalid data
since none of the users are actually connected.
