### ISSUE TITLE
What is stored where and how? 

### ISSUE THREAD

**Issue by telion2** [an-sh/chat-service#8]
Nice package here!
I was wondering how all the data is stored. Background are the following questions: 

- Where is everything stored exactly? On my server? Some other server?  In some files/db?  In memory? If my server completely shuts down, can Chat-service still recover or only if the chat-service process is down?
- What do I need to store in a own database to ensure proper functionality of the service, even by a full server shutdown etc.? 
- While we are at it: Is there a way to initialize Chat-service based on the contents of a DB? Or do I need to repeat each client Request? Can I export the stores of Chat-service so I can initialize Chat-service based on them? 
- What is the maximum memory of Chat-Service? (Considering a very high number of Messages in a Room) 

Thank you ;)

**Comment by an-sh** [comment]
Hi,

Everything can be stored in memory on in Redis. It is done via an
adapter (MemoryState.js/RedisState.js), also in theory any other
storage can be added. Memory limits are depending on the db and it
design, i don't have any measures. In case of service instance crash,
there will be some inconsistency due to the fact that presence
information will be incorrect, so there is a need to run some recovery
functions.
